metttta
MulverineX/legacy-settings-icons pull request #3
Opened 2020-10-31 00:15 UTC by Snapperito

2020-10-31 00:48 UTC, MulverineX requested changes
missed the space on the description

2020-10-31 01:28 UTC, Snapperito commented
oo p s

2020-10-31 01:28 UTC, Snapperito commented
figgezed

2021-01-24 22:32 UTC, MulverineX approved these changes

2021-01-24 22:32 UTC, merged